# WANDB_MODE=dryrun
CUDA_VISIBLE_DEVICES=2 python self-paced-RL-coloc-scale-joint.py \
                       --savename  coloc_rl_seq10_scale_ent12_joint_lr1e03_2fc5conv_ARLarger \
                       --pretrained cluttermnistARLarger_m60_trip_SGD_scale_anchorsmp_2fc5conv/best.pth.tar \
                       --evaluate 0 \
                       --digit 4 \
                       --lr_ag 0.001 \
                       --lr 0.001 \
                       --sparse 0 \
                       --pooling_mode align \
                       --pooling_size 5 \
                       --lamb_ent 12. \
                       --lamb_int 0. \
                       --seq_len 10 \
                       --margin 60 \
                       --sign 0 \
                       --hidden_size 48 \
                       --freeze 0 \
                       --norm 0 \
                       --num_act 14 \
                       --optimizer_ag Adam \
                       --optimizer SGD \
                       --epochs 250 \
                       --batch_size 512 \
                       --step_ag 80 \
                       --steps 30 70 110
