CUDA_VISIBLE_DEVICES=4 python train-newdigit.py \
                       --savename ordinal_ae_fewshot_digit2_supp4000_ent05_trainpatch_shufprotoemb_shufprotoRew_ftclutter \
                       --pretrained_agent ordinal_ae_proj_seq10_ent6_lr1e03_stp80_50_digit3_randpatch_shufprotoemb_shufprotoRew_supp5/best.pth.tar \
                       --pretrained pretrain_ae_ord_proj_50_lr1e03_scp5_digit3_lamb01_randpatch_stp80_shuffle_proto/last.pth.tar \
                       --evaluate 0 \
                       --support_size 4000 \
                       --bg_name moreclutter \
                       --sample_size whole \
                       --digit 2 \
                       --rnn 1 \
                       --lr_ag 0.001 \
                       --pooling_mode align \
                       --pooling_size 7 \
                       --lamb_ent 0.5 \
                       --lamb_int 0. \
                       --seq_len 10 \
                       --margin 60 \
                       --hidden_size 48 \
                       --freeze 1 \
                       --norm 0 \
                       --num_act 10 \
                       --patience 50 \
                       --optimizer_ag Adam \
                       --epochs 100 \
                       --batch_size 512 \
                       --step_ag 80

CUDA_VISIBLE_DEVICES=4 python train-newdigit.py \
                       --savename ordinal_ae_fewshot_digit2_supp4000_ent05_trainpatch_shufprotoemb_shufprotoRew_ftclutter_r2 \
                       --pretrained_agent ordinal_ae_proj_seq10_ent6_lr1e03_stp80_50_digit3_randpatch_shufprotoemb_shufprotoRew_supp5/best.pth.tar \
                       --pretrained pretrain_ae_ord_proj_50_lr1e03_scp5_digit3_lamb01_randpatch_stp80_shuffle_proto/last.pth.tar \
                       --evaluate 0 \
                       --support_size 4000 \
                       --bg_name moreclutter \
                       --sample_size whole \
                       --digit 2 \
                       --rnn 1 \
                       --lr_ag 0.001 \
                       --pooling_mode align \
                       --pooling_size 7 \
                       --lamb_ent 0.5 \
                       --lamb_int 0. \
                       --seq_len 10 \
                       --margin 60 \
                       --hidden_size 48 \
                       --freeze 1 \
                       --norm 0 \
                       --num_act 10 \
                       --patience 50 \
                       --optimizer_ag Adam \
                       --epochs 100 \
                       --batch_size 512 \
                       --step_ag 80

CUDA_VISIBLE_DEVICES=4 python train-newdigit.py \
                       --savename ordinal_ae_fewshot_digit2_supp4000_ent05_trainpatch_shufprotoemb_shufprotoRew_ftclutter_r3 \
                       --pretrained_agent ordinal_ae_proj_seq10_ent6_lr1e03_stp80_50_digit3_randpatch_shufprotoemb_shufprotoRew_supp5/best.pth.tar \
                       --pretrained pretrain_ae_ord_proj_50_lr1e03_scp5_digit3_lamb01_randpatch_stp80_shuffle_proto/last.pth.tar \
                       --evaluate 0 \
                       --support_size 4000 \
                       --bg_name moreclutter \
                       --sample_size whole \
                       --digit 2 \
                       --rnn 1 \
                       --lr_ag 0.001 \
                       --pooling_mode align \
                       --pooling_size 7 \
                       --lamb_ent 0.5 \
                       --lamb_int 0. \
                       --seq_len 10 \
                       --margin 60 \
                       --hidden_size 48 \
                       --freeze 1 \
                       --norm 0 \
                       --num_act 10 \
                       --patience 50 \
                       --optimizer_ag Adam \
                       --epochs 100 \
                       --batch_size 512 \
                       --step_ag 80

CUDA_VISIBLE_DEVICES=4 python train-newdigit.py \
                       --savename ordinal_ae_fewshot_digit2_supp4000_ent05_trainpatch_shufprotoemb_shufprotoRew_ftclutter_r4 \
                       --pretrained_agent ordinal_ae_proj_seq10_ent6_lr1e03_stp80_50_digit3_randpatch_shufprotoemb_shufprotoRew_supp5/best.pth.tar \
                       --pretrained pretrain_ae_ord_proj_50_lr1e03_scp5_digit3_lamb01_randpatch_stp80_shuffle_proto/last.pth.tar \
                       --evaluate 0 \
                       --support_size 4000 \
                       --bg_name moreclutter \
                       --sample_size whole \
                       --digit 2 \
                       --rnn 1 \
                       --lr_ag 0.001 \
                       --pooling_mode align \
                       --pooling_size 7 \
                       --lamb_ent 0.5 \
                       --lamb_int 0. \
                       --seq_len 10 \
                       --margin 60 \
                       --hidden_size 48 \
                       --freeze 1 \
                       --norm 0 \
                       --num_act 10 \
                       --patience 50 \
                       --optimizer_ag Adam \
                       --epochs 100 \
                       --batch_size 512 \
                       --step_ag 80

CUDA_VISIBLE_DEVICES=4 python train-newdigit.py \
                       --savename ordinal_ae_fewshot_digit2_supp4000_ent05_trainpatch_shufprotoemb_shufprotoRew_ftclutter_r5 \
                       --pretrained_agent ordinal_ae_proj_seq10_ent6_lr1e03_stp80_50_digit3_randpatch_shufprotoemb_shufprotoRew_supp5/best.pth.tar \
                       --pretrained pretrain_ae_ord_proj_50_lr1e03_scp5_digit3_lamb01_randpatch_stp80_shuffle_proto/last.pth.tar \
                       --evaluate 0 \
                       --support_size 4000 \
                       --bg_name moreclutter \
                       --sample_size whole \
                       --digit 2 \
                       --rnn 1 \
                       --lr_ag 0.001 \
                       --pooling_mode align \
                       --pooling_size 7 \
                       --lamb_ent 0.5 \
                       --lamb_int 0. \
                       --seq_len 10 \
                       --margin 60 \
                       --hidden_size 48 \
                       --freeze 1 \
                       --norm 0 \
                       --num_act 10 \
                       --patience 50 \
                       --optimizer_ag Adam \
                       --epochs 100 \
                       --batch_size 512 \
                       --step_ag 80

